theme: jekyll-theme-minimal
title: Abhinav Gopal
description: Welcome to my personal site! Here, you can find out more about my interests, hobbies, and ideas.
avatar: ./profile.png

author:
  name: Abhinav Gopal
  avatar: ./profile.png
