theme: jekyll-theme-minimal
title: Abhinav Gopal
description: Welcome to my personal site! Here, you can find out more about my interests, hobbies, and ideas.
avatar: ./'Screen Shot 2020-12-02 at 3.52.49 PM.png'
